plugins:
  - fp
  - jsdoc

settings:
  jsdoc:
    tagNamePreference:
      returns: return

rules:
  no-var: off
  no-cond-assign: off
  no-negated-condition: error
  # fp/no-arguments: error
  fp/no-class: error
  fp/no-delete: error
  fp/no-events: error
  fp/no-get-set: error
  # fp/no-let: error
  # fp/no-loops: error
  # fp/no-mutating-assign: error
  # fp/no-mutating-methods: error
  # fp/no-mutation: error
  # fp/no-nil: error
  fp/no-proxy: error
  fp/no-rest-parameters: error
  fp/no-this: error
  fp/no-throw: error
  # fp/no-unused-expression: error
  # fp/no-valueof-field: error

  jsdoc/check-alignment: 1
  jsdoc/check-examples: 1
  jsdoc/check-indentation: 1
  jsdoc/check-param-names: 1
  jsdoc/check-syntax: 1
  jsdoc/check-tag-names: 1
  jsdoc/check-types: 1
  # jsdoc/newline-after-description: 1
  jsdoc/no-undefined-types: 1
  # jsdoc/require-description: 1
  jsdoc/require-description-complete-sentence: 1
  # jsdoc/require-example: 1
  jsdoc/require-hyphen-before-param-description: 1
  jsdoc/require-param: 1
  # jsdoc/require-param-description: 1
  jsdoc/require-param-name: 1
  jsdoc/require-param-type: 1
  jsdoc/require-returns: 1
  jsdoc/require-returns-check: 1
  # jsdoc/require-returns-description: 1
  jsdoc/require-returns-type: 1
  jsdoc/valid-types: 1
