rules:
  no-negated-condition: off
  fp/no-arguments: off
  fp/no-class: off
  fp/no-delete: off
  fp/no-events: off
  fp/no-get-set: off
  fp/no-let: off
  fp/no-loops: off
  fp/no-mutating-assign: off
  fp/no-mutating-methods: off
  fp/no-mutation: off
  fp/no-nil: off
  fp/no-proxy: off
  fp/no-rest-parameters: off
  fp/no-this: off
  fp/no-throw: off
  fp/no-unused-expression: off
  fp/no-valueof-field: off
  jsdoc/check-alignment: off
  jsdoc/check-examples: off
  jsdoc/check-indentation: off
  jsdoc/check-param-names: off
  jsdoc/check-syntax: off
  jsdoc/check-tag-names: off
  jsdoc/check-types: off
  jsdoc/newline-after-description: off
  jsdoc/no-undefined-types: off
  jsdoc/require-description: off
  jsdoc/require-description-complete-sentence: off
  jsdoc/require-example: off
  jsdoc/require-hyphen-before-param-description: off
  jsdoc/require-param: off
  jsdoc/require-param-description: off
  jsdoc/require-param-name: off
  jsdoc/require-param-type: off
  jsdoc/require-returns: off
  jsdoc/require-returns-check: off
  jsdoc/require-returns-description: off
  jsdoc/require-returns-type: off
  jsdoc/valid-types: off
